<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Donation;
use Carbon\Carbon;

class DonationSeeder extends Seeder
{
    public function run()
    {
        Donation::insert([
            [
                'organization_id' => 1,
                'compaign_ID' => 1,
                'donor_firstName' => 'Ali',
                'donor_lastName' => 'Benali',
                'donor_phoneNumber' => '0550123456',
                'donor_email' => 'ali.benali@example.com',
                'donation_type' => 'money',
                'donation_amount' => 5000,
                'donation_received' => true,
                'donation_date' => Carbon::parse('2024-12-15'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 1,
                'compaign_ID' => 2,
                'donor_firstName' => 'Sara',
                'donor_lastName' => 'Khelifi',
                'donor_phoneNumber' => '0660987654',
                'donor_email' => 'sara.khelifi@example.com',
                'donation_type' => 'other',
                'donation_amount' => null,
                'donation_received' => true,
                'donation_date' => Carbon::parse('2024-12-10'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 1,
                'compaign_ID' => 3,
                'donor_firstName' => 'Mohamed',
                'donor_lastName' => 'Amrani',
                'donor_phoneNumber' => '0770456123',
                'donor_email' => 'mohamed.amrani@example.com',
                'donation_type' => 'money',
                'donation_amount' => 10000,
                'donation_received' => true,
                'donation_date' => Carbon::parse('2024-12-08'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 1,
                'compaign_ID' => 4,
                'donor_firstName' => 'Lina',
                'donor_lastName' => 'Toumi',
                'donor_phoneNumber' => '0541122334',
                'donor_email' => 'lina.toumi@example.com',
                'donation_type' => 'money',
                'donation_amount' => 7500,
                'donation_received' => false,
                'donation_date' => Carbon::parse('2024-12-20'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 1,
                'compaign_ID' => 5,
                'donor_firstName' => 'Fatima',
                'donor_lastName' => 'Djerad',
                'donor_phoneNumber' => '0650555666',
                'donor_email' => 'fatima.djerad@example.com',
                'donation_type' => 'other',
                'donation_amount' => null,
                'donation_received' => true,
                'donation_date' => Carbon::parse('2024-12-12'),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ===== ORG 2: YOUTH EDUCATION NETWORK =====
            [
                'organization_id' => 2,
                'compaign_ID' => 7,
                'donor_firstName' => 'Karim',
                'donor_lastName' => 'Boulahrouz',
                'donor_phoneNumber' => '0560777888',
                'donor_email' => 'karim.boulahrouz@example.com',
                'donation_type' => 'money',
                'donation_amount' => 15000,
                'donation_received' => true,
                'donation_date' => Carbon::parse('2024-12-14'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 2,
                'compaign_ID' => 8,
                'donor_firstName' => 'Yasmin',
                'donor_lastName' => 'Haddad',
                'donor_phoneNumber' => '0680999000',
                'donor_email' => 'yasmin.haddad@example.com',
                'donation_type' => 'other',
                'donation_amount' => null,
                'donation_received' => true,
                'donation_date' => Carbon::parse('2024-12-11'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 2,
                'compaign_ID' => 9,
                'donor_firstName' => 'Nabil',
                'donor_lastName' => 'Saidi',
                'donor_phoneNumber' => '0771111222',
                'donor_email' => 'nabil.saidi@example.com',
                'donation_type' => 'money',
                'donation_amount' => 20000,
                'donation_received' => false,
                'donation_date' => Carbon::parse('2024-12-18'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 2,
                'compaign_ID' => 10,
                'donor_firstName' => 'Amira',
                'donor_lastName' => 'Belaid',
                'donor_phoneNumber' => '0652222333',
                'donor_email' => 'amira.belaid@example.com',
                'donation_type' => 'money',
                'donation_amount' => 8000,
                'donation_received' => true,
                'donation_date' => Carbon::parse('2024-12-09'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 2,
                'compaign_ID' => 11,
                'donor_firstName' => 'Hamza',
                'donor_lastName' => 'Zahra',
                'donor_phoneNumber' => '0763333444',
                'donor_email' => 'hamza.zahra@example.com',
                'donation_type' => 'other',
                'donation_amount' => null,
                'donation_received' => true,
                'donation_date' => Carbon::parse('2024-12-13'),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ===== ORG 3: HOPE MEDICAL AID =====
            [
                'organization_id' => 3,
                'compaign_ID' => 13,
                'donor_firstName' => 'Dr. Ahmed',
                'donor_lastName' => 'Mostefai',
                'donor_phoneNumber' => '0550444555',
                'donor_email' => 'dr.ahmed.mostefai@example.com',
                'donation_type' => 'medicine',
                'donation_amount' => null,
                'donation_received' => true,
                'donation_date' => Carbon::parse('2024-12-16'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 3,
                'compaign_ID' => 14,
                'donor_firstName' => 'Zohra',
                'donor_lastName' => 'Benmessaoud',
                'donor_phoneNumber' => '0670555666',
                'donor_email' => 'zohra.benmessaoud@example.com',
                'donation_type' => 'money',
                'donation_amount' => 25000,
                'donation_received' => true,
                'donation_date' => Carbon::parse('2024-12-12'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 3,
                'compaign_ID' => 15,
                'donor_firstName' => 'Ibrahim',
                'donor_lastName' => 'Soudani',
                'donor_phoneNumber' => '0781666777',
                'donor_email' => 'ibrahim.soudani@example.com',
                'donation_type' => 'other',
                'donation_amount' => null,
                'donation_received' => false,
                'donation_date' => Carbon::parse('2024-12-19'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 3,
                'compaign_ID' => 16,
                'donor_firstName' => 'Rania',
                'donor_lastName' => 'Khadjaoui',
                'donor_phoneNumber' => '0640777888',
                'donor_email' => 'rania.khadjaoui@example.com',
                'donation_type' => 'money',
                'donation_amount' => 12000,
                'donation_received' => true,
                'donation_date' => Carbon::parse('2024-12-10'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 3,
                'compaign_ID' => 17,
                'donor_firstName' => 'Salim',
                'donor_lastName' => 'Chakour',
                'donor_phoneNumber' => '0761888999',
                'donor_email' => 'salim.chakour@example.com',
                'donation_type' => 'medicine',
                'donation_amount' => null,
                'donation_received' => true,
                'donation_date' => Carbon::parse('2024-12-14'),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ===== ORG 4: CLEAN COAST ALGERIA =====
            [
                'organization_id' => 4,
                'compaign_ID' => 19,
                'donor_firstName' => 'Imane',
                'donor_lastName' => 'Bouaziz',
                'donor_phoneNumber' => '0550900111',
                'donor_email' => 'imane.bouaziz@example.com',
                'donation_type' => 'money',
                'donation_amount' => 6000,
                'donation_received' => true,
                'donation_date' => Carbon::parse('2024-12-11'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 4,
                'compaign_ID' => 20,
                'donor_firstName' => 'Rashid',
                'donor_lastName' => 'Benabid',
                'donor_phoneNumber' => '0672111222',
                'donor_email' => 'rashid.benabid@example.com',
                'donation_type' => 'other',
                'donation_amount' => null,
                'donation_received' => true,
                'donation_date' => Carbon::parse('2024-12-15'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 4,
                'compaign_ID' => 21,
                'donor_firstName' => 'Leila',
                'donor_lastName' => 'Dekhane',
                'donor_phoneNumber' => '0793222333',
                'donor_email' => 'leila.dekhane@example.com',
                'donation_type' => 'money',
                'donation_amount' => 9000,
                'donation_received' => false,
                'donation_date' => Carbon::parse('2024-12-21'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 4,
                'compaign_ID' => 22,
                'donor_firstName' => 'Tarek',
                'donor_lastName' => 'Bachir',
                'donor_phoneNumber' => '0654333444',
                'donor_email' => 'tarek.bachir@example.com',
                'donation_type' => 'other',
                'donation_amount' => null,
                'donation_received' => true,
                'donation_date' => Carbon::parse('2024-12-13'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 4,
                'compaign_ID' => 23,
                'donor_firstName' => 'Nora',
                'donor_lastName' => 'Laroui',
                'donor_phoneNumber' => '0765444555',
                'donor_email' => 'nora.laroui@example.com',
                'donation_type' => 'money',
                'donation_amount' => 11000,
                'donation_received' => true,
                'donation_date' => Carbon::parse('2024-12-17'),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ===== ORG 5: ALGERIAN WOMEN EMPOWERMENT =====
            [
                'organization_id' => 5,
                'compaign_ID' => 25,
                'donor_firstName' => 'Hana',
                'donor_lastName' => 'Mecheri',
                'donor_phoneNumber' => '0550555666',
                'donor_email' => 'hana.mecheri@example.com',
                'donation_type' => 'money',
                'donation_amount' => 18000,
                'donation_received' => true,
                'donation_date' => Carbon::parse('2024-12-12'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 5,
                'compaign_ID' => 26,
                'donor_firstName' => 'Fadi',
                'donor_lastName' => 'Soleimani',
                'donor_phoneNumber' => '0673666777',
                'donor_email' => 'fadi.soleimani@example.com',
                'donation_type' => 'other',
                'donation_amount' => null,
                'donation_received' => true,
                'donation_date' => Carbon::parse('2024-12-08'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 5,
                'compaign_ID' => 27,
                'donor_firstName' => 'Samira',
                'donor_lastName' => 'Abdessalam',
                'donor_phoneNumber' => '0784777888',
                'donor_email' => 'samira.abdessalam@example.com',
                'donation_type' => 'money',
                'donation_amount' => 14000,
                'donation_received' => false,
                'donation_date' => Carbon::parse('2024-12-22'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 5,
                'compaign_ID' => 28,
                'donor_firstName' => 'Wiam',
                'donor_lastName' => 'Ouadhia',
                'donor_phoneNumber' => '0651888999',
                'donor_email' => 'wiam.ouadhia@example.com',
                'donation_type' => 'money',
                'donation_amount' => 10000,
                'donation_received' => true,
                'donation_date' => Carbon::parse('2024-12-16'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 5,
                'compaign_ID' => 29,
                'donor_firstName' => 'Jamal',
                'donor_lastName' => 'Ouali',
                'donor_phoneNumber' => '0762999000',
                'donor_email' => 'jamal.ouali@example.com',
                'donation_type' => 'other',
                'donation_amount' => null,
                'donation_received' => true,
                'donation_date' => Carbon::parse('2024-12-11'),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ===== ORG 6: HEALTHY KIDS INITIATIVE =====
            [
                'organization_id' => 6,
                'compaign_ID' => 31,
                'donor_firstName' => 'Dina',
                'donor_lastName' => 'Hassani',
                'donor_phoneNumber' => '0550000111',
                'donor_email' => 'dina.hassani@example.com',
                'donation_type' => 'money',
                'donation_amount' => 8500,
                'donation_received' => true,
                'donation_date' => Carbon::parse('2024-12-14'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 6,
                'compaign_ID' => 32,
                'donor_firstName' => 'Bilal',
                'donor_lastName' => 'Aissaoui',
                'donor_phoneNumber' => '0670111222',
                'donor_email' => 'bilal.aissaoui@example.com',
                'donation_type' => 'other',
                'donation_amount' => null,
                'donation_received' => true,
                'donation_date' => Carbon::parse('2024-12-09'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 6,
                'compaign_ID' => 33,
                'donor_firstName' => 'Salma',
                'donor_lastName' => 'Belkhier',
                'donor_phoneNumber' => '0791222333',
                'donor_email' => 'salma.belkhier@example.com',
                'donation_type' => 'money',
                'donation_amount' => 16000,
                'donation_received' => true,
                'donation_date' => Carbon::parse('2024-12-18'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 6,
                'compaign_ID' => 34,
                'donor_firstName' => 'Khaled',
                'donor_lastName' => 'Cheikh',
                'donor_phoneNumber' => '0652333444',
                'donor_email' => 'khaled.cheikh@example.com',
                'donation_type' => 'medicine',
                'donation_amount' => null,
                'donation_received' => false,
                'donation_date' => Carbon::parse('2024-12-23'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 6,
                'compaign_ID' => 35,
                'donor_firstName' => 'Mounira',
                'donor_lastName' => 'Rezki',
                'donor_phoneNumber' => '0763444555',
                'donor_email' => 'mounira.rezki@example.com',
                'donation_type' => 'money',
                'donation_amount' => 7000,
                'donation_received' => true,
                'donation_date' => Carbon::parse('2024-12-13'),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ===== ORG 7: SHELTER FOR HOMELESS =====
            [
                'organization_id' => 7,
                'compaign_ID' => 37,
                'donor_firstName' => 'Hassan',
                'donor_lastName' => 'Yahiaoui',
                'donor_phoneNumber' => '0550555666',
                'donor_email' => 'hassan.yahiaoui@example.com',
                'donation_type' => 'money',
                'donation_amount' => 22000,
                'donation_received' => true,
                'donation_date' => Carbon::parse('2024-12-10'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 7,
                'compaign_ID' => 38,
                'donor_firstName' => 'Zainab',
                'donor_lastName' => 'Bouhellal',
                'donor_phoneNumber' => '0672666777',
                'donor_email' => 'zainab.bouhellal@example.com',
                'donation_type' => 'food',
                'donation_amount' => null,
                'donation_received' => true,
                'donation_date' => Carbon::parse('2024-12-15'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 7,
                'compaign_ID' => 39,
                'donor_firstName' => 'Osama',
                'donor_lastName' => 'Belghorbi',
                'donor_phoneNumber' => '0783777888',
                'donor_email' => 'osama.belghorbi@example.com',
                'donation_type' => 'money',
                'donation_amount' => 13000,
                'donation_received' => false,
                'donation_date' => Carbon::parse('2024-12-20'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 7,
                'compaign_ID' => 40,
                'donor_firstName' => 'Nadia',
                'donor_lastName' => 'Mansour',
                'donor_phoneNumber' => '0640888999',
                'donor_email' => 'nadia.mansour@example.com',
                'donation_type' => 'other',
                'donation_amount' => null,
                'donation_received' => true,
                'donation_date' => Carbon::parse('2024-12-12'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 7,
                'compaign_ID' => 41,
                'donor_firstName' => 'Rachid',
                'donor_lastName' => 'Ghedir',
                'donor_phoneNumber' => '0761999000',
                'donor_email' => 'rachid.ghedir@example.com',
                'donation_type' => 'money',
                'donation_amount' => 9500,
                'donation_received' => true,
                'donation_date' => Carbon::parse('2024-12-17'),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ===== ORG 8: WATER FOR LIFE =====
            [
                'organization_id' => 8,
                'compaign_ID' => 43,
                'donor_firstName' => 'Safia',
                'donor_lastName' => 'Kaci',
                'donor_phoneNumber' => '0550111222',
                'donor_email' => 'safia.kaci@example.com',
                'donation_type' => 'money',
                'donation_amount' => 19000,
                'donation_received' => true,
                'donation_date' => Carbon::parse('2024-12-16'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 8,
                'compaign_ID' => 44,
                'donor_firstName' => 'Younes',
                'donor_lastName' => 'Guerfi',
                'donor_phoneNumber' => '0673222333',
                'donor_email' => 'younes.guerfi@example.com',
                'donation_type' => 'other',
                'donation_amount' => null,
                'donation_received' => true,
                'donation_date' => Carbon::parse('2024-12-11'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 8,
                'compaign_ID' => 45,
                'donor_firstName' => 'Soumia',
                'donor_lastName' => 'Mesghouni',
                'donor_phoneNumber' => '0784333444',
                'donor_email' => 'soumia.mesghouni@example.com',
                'donation_type' => 'money',
                'donation_amount' => 15500,
                'donation_received' => false,
                'donation_date' => Carbon::parse('2024-12-24'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 8,
                'compaign_ID' => 46,
                'donor_firstName' => 'Aziz',
                'donor_lastName' => 'Boulares',
                'donor_phoneNumber' => '0651444555',
                'donor_email' => 'aziz.boulares@example.com',
                'donation_type' => 'other',
                'donation_amount' => null,
                'donation_received' => true,
                'donation_date' => Carbon::parse('2024-12-14'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 8,
                'compaign_ID' => 47,
                'donor_firstName' => 'Kaoutar',
                'donor_lastName' => 'Tatar',
                'donor_phoneNumber' => '0762555666',
                'donor_email' => 'kaoutar.tatar@example.com',
                'donation_type' => 'money',
                'donation_amount' => 11500,
                'donation_received' => true,
                'donation_date' => Carbon::parse('2024-12-19'),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ===== ORG 9: FOOD BANK ALGERIA =====
            [
                'organization_id' => 9,
                'compaign_ID' => 49,
                'donor_firstName' => 'Habiba',
                'donor_lastName' => 'Boudaoud',
                'donor_phoneNumber' => '0550222333',
                'donor_email' => 'habiba.boudaoud@example.com',
                'donation_type' => 'money',
                'donation_amount' => 30000,
                'donation_received' => true,
                'donation_date' => Carbon::parse('2024-12-09'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 9,
                'compaign_ID' => 50,
                'donor_firstName' => 'Adel',
                'donor_lastName' => 'Tamtam',
                'donor_phoneNumber' => '0674333444',
                'donor_email' => 'adel.tamtam@example.com',
                'donation_type' => 'food',
                'donation_amount' => null,
                'donation_received' => true,
                'donation_date' => Carbon::parse('2024-12-13'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 9,
                'compaign_ID' => 51,
                'donor_firstName' => 'Hend',
                'donor_lastName' => 'Hamidane',
                'donor_phoneNumber' => '0785444555',
                'donor_email' => 'hend.hamidane@example.com',
                'donation_type' => 'money',
                'donation_amount' => 21000,
                'donation_received' => false,
                'donation_date' => Carbon::parse('2024-12-25'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 9,
                'compaign_ID' => 52,
                'donor_firstName' => 'Saif',
                'donor_lastName' => 'Bouaziz',
                'donor_phoneNumber' => '0642555666',
                'donor_email' => 'saif.bouaziz@example.com',
                'donation_type' => 'food',
                'donation_amount' => null,
                'donation_received' => true,
                'donation_date' => Carbon::parse('2024-12-10'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 9,
                'compaign_ID' => 53,
                'donor_firstName' => 'Intissar',
                'donor_lastName' => 'Medel',
                'donor_phoneNumber' => '0763666777',
                'donor_email' => 'intissar.medel@example.com',
                'donation_type' => 'money',
                'donation_amount' => 17500,
                'donation_received' => true,
                'donation_date' => Carbon::parse('2024-12-15'),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ===== ORG 10: MENTAL HEALTH AWARENESS =====
            [
                'organization_id' => 10,
                'compaign_ID' => 55,
                'donor_firstName' => 'Lyes',
                'donor_lastName' => 'Medel',
                'donor_phoneNumber' => '0550333444',
                'donor_email' => 'lyes.medel@example.com',
                'donation_type' => 'money',
                'donation_amount' => 12500,
                'donation_received' => true,
                'donation_date' => Carbon::parse('2024-12-12'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 10,
                'compaign_ID' => 56,
                'donor_firstName' => 'Hibat',
                'donor_lastName' => 'Sallah',
                'donor_phoneNumber' => '0675444555',
                'donor_email' => 'hibat.sallah@example.com',
                'donation_type' => 'other',
                'donation_amount' => null,
                'donation_received' => true,
                'donation_date' => Carbon::parse('2024-12-16'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 10,
                'compaign_ID' => 57,
                'donor_firstName' => 'Amine',
                'donor_lastName' => 'Karim',
                'donor_phoneNumber' => '0786555666',
                'donor_email' => 'amine.karim@example.com',
                'donation_type' => 'money',
                'donation_amount' => 18500,
                'donation_received' => false,
                'donation_date' => Carbon::parse('2024-12-21'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 10,
                'compaign_ID' => 58,
                'donor_firstName' => 'Reem',
                'donor_lastName' => 'Rabie',
                'donor_phoneNumber' => '0643666777',
                'donor_email' => 'reem.rabie@example.com',
                'donation_type' => 'medicine',
                'donation_amount' => null,
                'donation_received' => true,
                'donation_date' => Carbon::parse('2024-12-11'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 10,
                'compaign_ID' => 59,
                'donor_firstName' => 'Tahar',
                'donor_lastName' => 'Abbou',
                'donor_phoneNumber' => '0764777888',
                'donor_email' => 'tahar.abbou@example.com',
                'donation_type' => 'money',
                'donation_amount' => 14500,
                'donation_received' => true,
                'donation_date' => Carbon::parse('2024-12-18'),
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);
    }
}